[target]
address = "example.org"

[http2]
  [http2.defaults]
  max_streams = 10
  window_size = 1024
  frame_size = 2048
  ha_pack_size = 1024

  [http2.clients.mobile]
  max_streams = 2
  window_size = 128

  [http2.clients.desktop]
  window_size = 4096

[scenarios]
  [scenarios.get_map]
  uris = [
    "/example/1",
    "/example/2",
  ]
  [scenarios.get_events]
  ammo = "./events.ammo"
  marker = "ev"

[schedules]
ramp = ["line(1, 10, 1m)", "const(10, 10m)"]
line = ["line(1, 30, 1m)"]

[bfg]
  [bfg.map]
  scenario = "&scenarios.get_map"
    [bfg.map.pools.mobile]
    target = "&target.address"
    connection = "&http2.clients.mobile"
    count = 35
    schedule = "&schedules.ramp"
    [bfg.map.pools.desktop]
    connection = "&http2.clients.desktop"
    count = "&schedules.line"  # linear growth for number of clients

  [bfg.events]
  scenario = "&scenarios.get_events"
    [bfg.events.pools.desktop]
    connection = "&http2.clients.desktop"
    schedule = "&schedules.ramp"
