[gun.mobile]
type = 'http2'
target = "http2.example.org"
max_streams = 2
window_size = 128

[ammo.myammo]
file = "./tmp/ammo.line"

[schedule]
ramp = ["line(1, 10, 10s)", "const(10, 10s)"]
line = ["line(1, 30, 1m)"]

[aggregator.caching]
uplinks = ["mongo://localhost"]

[bfg.mobile]
gun = "mobile"
instances = 2
schedule = "ramp"
aggregator = "caching"
ammo = "myammo"

[bfg.mobile2]
gun = "mobile"
instances = 4
schedule = "ramp"
aggregator = "caching"
ammo = "myammo"
